- title: Well Established
  items:
    - DevOps
    - Distributed computing
    - Scalable architectures
    - Microservices
    - Search technologies
    - Complex event processing
    - Stream processing
    - Continuous delivery
    - Centralised logging
    - Containerisation
    - CQRS
    - Event sourcing
    - Functional programming
    - Reactive programming
    - Deep Learning (AI)
    - Data science
    - Internet of Things
    - PAAS expertise
    - API management
    - AngularJS
    - Node.js
- title: Recently Gained
  items:
    - NAO Robotics
    - Microcontrollers
    - Process engines
    - Node-Red
    - Kafka
    - ReactJS
    - Angular 2
    - Vue.js
    - Homie (Marvin Roger)
- title: On Our Radar
  items:
    - Smart Machines
    - Industrial Internet of Things
    - Elixir
    - Fog / Edge computing
    - Flogo
    - Kaa IoT platform
    - Lagom (Lightbend)
- title: Methodologies
  items:
    - Domain Driven Design
    - Test Driven Development
    - Agile
    - XP
- title: Architectures
  items:
    - Cloud-native
    - Service oriented
    - Microservice
    - Model View Controller
    - Lambda
    - Kappa
