- title: Well Established
  items:
    - DevOps
    - Distributed computing
    - Search technologies
    - Scalable architectures
    - Complex event processing
    - Continuous delivery
    - Centralised logging
    - Containerisation
    - Microservices
    - Event sourcing
    - CQRS
- title: Recently Gained
  items:
    - Functional programming
    - Reactive programming
    - Data science
    - PAAS expertise
    - API management
    - Internet of Things
    - Stream processing
    - NAO Robotics
- title: On Our Radar
  items:
    - Deep Learning (AI)
    - Smart Machines
    - Industrial Internet of Things
- title: Methodologies
  items:
    - Domain Driven Design
    - Test Driven Development
    - Agile
    - XP
- title: Architectures
  items:
    - Cloud-native
    - Service oriented
    - Microservice
    - Model View Controller
    - Lambda
    - Kappa
