- title: Well Established
  items:
    - DevOps
    - Distributed computing
    - Scalable architectures
    - Microservices
    - Search technologies
    - Complex event processing
    - Stream processing
    - Continuous delivery
    - Centralised logging
    - Containerisation
    - CQRS
    - Event sourcing
    - Functional programming
    - Reactive programming
    - Deep Learning (AI)
    - Data science
    - Internet of Things
    - PAAS expertise
    - API management
    - AngularJS
    - Node.js
- title: Recently Gained
  items:
    - NAO Robotics
    - Microcontrollers
    - Process engines
    - Node-Red
    - Kafka
    - ReactJS
    - Angular 2
    - Vue.js
    - Homie (Marvin Roger)
    - Elixir
- title: On Our Radar
  items:
    - Lagom (Lightbend)
    - Edge computing
    - IoT platforms
    - NB-IoT
    - Nerves
    - VR/AR
    - Blockchain
- title: Methodologies
  items:
    - Domain Driven Design
    - Test Driven Development
    - Agile
    - XP
- title: Architectures
  items:
    - Cloud-native
    - Microservices
    - Service oriented
    - Model View Controller
    - Lambda
    - Kappa
